//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myRecipeBook.Exception {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessagesException {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessagesException() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("myRecipeBook.Exception.ResourceMessagesException", typeof(ResourceMessagesException).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid email format. Please Check!.
        /// </summary>
        public static string INVALID_EMAIL_FORMAT {
            get {
                return ResourceManager.GetString("INVALID_EMAIL_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Internal server error! Please check!.
        /// </summary>
        public static string UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Access Token Required! Please Check!.
        /// </summary>
        public static string VALIDATION_ACCESS_TOKEN_REQUIRED {
            get {
                return ResourceManager.GetString("VALIDATION_ACCESS_TOKEN_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a At least one ingredient is required..
        /// </summary>
        public static string VALIDATION_AT_LAST_ONE_INGREDIENT {
            get {
                return ResourceManager.GetString("VALIDATION_AT_LAST_ONE_INGREDIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ingredient item is required! Please Verify..
        /// </summary>
        public static string VALIDATION_AT_LAST_ONE_INSTRUCTION {
            get {
                return ResourceManager.GetString("VALIDATION_AT_LAST_ONE_INSTRUCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid cook time value..
        /// </summary>
        public static string VALIDATION_COOKTIME_INVALID {
            get {
                return ResourceManager.GetString("VALIDATION_COOKTIME_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The current password is incorrect, please verify!.
        /// </summary>
        public static string VALIDATION_CURRENT_PASSWORD {
            get {
                return ResourceManager.GetString("VALIDATION_CURRENT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Recipe title must not exceed 500 characters..
        /// </summary>
        public static string VALIDATION_DESCRIPTION_EXCEED_QTYMAX_CHARACTERS {
            get {
                return ResourceManager.GetString("VALIDATION_DESCRIPTION_EXCEED_QTYMAX_CHARACTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid dish type value..
        /// </summary>
        public static string VALIDATION_DISHTYPE_INVALID {
            get {
                return ResourceManager.GetString("VALIDATION_DISHTYPE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email already registered in the database; please choose another one!.
        /// </summary>
        public static string VALIDATION_EMAIL_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("VALIDATION_EMAIL_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email is required. Please check!.
        /// </summary>
        public static string VALIDATION_EMAIL_REQUERID {
            get {
                return ResourceManager.GetString("VALIDATION_EMAIL_REQUERID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ingredient is required, can&apos;t  be empty..
        /// </summary>
        public static string VALIDATION_INGREDIENT_EMPTY {
            get {
                return ResourceManager.GetString("VALIDATION_INGREDIENT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please inform last one  Ingredient item is required! Please Verify..
        /// </summary>
        public static string VALIDATION_INGREDIENT_ITEM_REQUIRED {
            get {
                return ResourceManager.GetString("VALIDATION_INGREDIENT_ITEM_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Instruction description is required..
        /// </summary>
        public static string VALIDATION_INSTRUCTION_DESCRIPTION_REQUIRED {
            get {
                return ResourceManager.GetString("VALIDATION_INSTRUCTION_DESCRIPTION_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Instruction order must be greater than zero..
        /// </summary>
        public static string VALIDATION_INSTRUCTION_ORDER_INVALID {
            get {
                return ResourceManager.GetString("VALIDATION_INSTRUCTION_ORDER_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a At least one instruction is required..
        /// </summary>
        public static string VALIDATION_INSTRUCTIONS_REQUIRED {
            get {
                return ResourceManager.GetString("VALIDATION_INSTRUCTIONS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid Login or Password, please verify  .
        /// </summary>
        public static string VALIDATION_LOGIN_INVALID {
            get {
                return ResourceManager.GetString("VALIDATION_LOGIN_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Name must not exceed 100 characters..
        /// </summary>
        public static string VALIDATION_NAME_EXCEED_QTY_CHARACTERS {
            get {
                return ResourceManager.GetString("VALIDATION_NAME_EXCEED_QTY_CHARACTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Name is required,Please check!.
        /// </summary>
        public static string VALIDATION_NAME_REQUIRED {
            get {
                return ResourceManager.GetString("VALIDATION_NAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The password must be 6 characters long. Please Verify!.
        /// </summary>
        public static string VALIDATION_PASSWORD_MIN_LENGTH {
            get {
                return ResourceManager.GetString("VALIDATION_PASSWORD_MIN_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Password must be at least 7 characters long. Please Check!.
        /// </summary>
        public static string VALIDATION_PASSWORD_MUST_QTY_CHARACTERS {
            get {
                return ResourceManager.GetString("VALIDATION_PASSWORD_MUST_QTY_CHARACTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Password is required. Please check!.
        /// </summary>
        public static string VALIDATION_PASSWORD_REQUERID {
            get {
                return ResourceManager.GetString("VALIDATION_PASSWORD_REQUERID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Recipe title is required. Please check!.
        /// </summary>
        public static string VALIDATION_RECIPE_TITLE_REQUIRED {
            get {
                return ResourceManager.GetString("VALIDATION_RECIPE_TITLE_REQUIRED", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a At least one dish type is required.
        /// </summary>
        public static string VALIDATION_RECIPE_DISHTYPES_REQUIRED {
            get {
                return ResourceManager.GetString("VALIDATION_RECIPE_DISHTYPES_REQUIRED", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a There are duplicated instruction orders. Each instruction must have a unique order.
        /// </summary>
        public static string VALIDATION_RECIPE_INSTRUCTION_ORDER_DUPLICATED {
            get {
                return ResourceManager.GetString("VALIDATION_RECIPE_INSTRUCTION_ORDER_DUPLICATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a You Don&apos;t have Access to this Resource. Please Check!.
        /// </summary>
        public static string VALIDATION_RESOURCE_ACCESS_DENIED {
            get {
                return ResourceManager.GetString("VALIDATION_RESOURCE_ACCESS_DENIED", resourceCulture);
            }
        }
    }
}
