name: CI

# Gatilhos de disparo para a branch develop e manual
on:
  workflow_dispatch:
  
  push:
    branches:
      - develop
      
  pull_request:
    branches:
      - develop

# Configura a subpasta padrão para todos os comandos de terminal (run)
#defaults:
#  run:
#    working-directory: ./meulivrodereceitas/

jobs:
  build-and-tests:
    name: Build and Tests
    runs-on: ubuntu-latest

    steps:
      # Passo obrigatório no GitHub Actions para baixar o código do repositório
      - name: Checkout code
        uses: actions/checkout@v4

      # Instalação do SDK do .NET 10
      - name: Installing .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      # Execução do Build (rodará automaticamente dentro de ./meulivrodereceitas)
      - name: Build
        run: dotnet build

      # Execução dos Testes (rodará automaticamente dentro de ./meulivrodereceitas)
      - name: Tests
        run: dotnet test
